#!/usr/bin/bash

if [[ $EUID -ne 0 ]];
then
    exec pkexec --disable-internal-agent "$0" "$@"
fi

rm -rf /boot/efi/*
rm -rf /boot/efi/.* || true
cp -r /.snapshots/.fr/bfr/efi/* /boot/efi/
cp -r /.snapshots/.fr/bfr/efi/.* /boot/efi/ || true
btrfs subvolume set-default /.snapshots/.fr/snapshot
